const translations = {
  // Ropa
  "T-Shirt": "Remera",
  "T-shirt": "Remera",
  Tshirt: "Remera",
  Shirt: "Camisa",
  Hoodie: "Buzo con capucha",
  Pullover: "Pullover",
  Jacket: "Campera",
  Coat: "Abrigo",
  Pants: "Pantalón",
  Jeans: "Jeans",
  Shorts: "Shorts",
  Dress: "Vestido",
  Skirt: "Falda",
  Shoes: "Zapatos",
  Sneakers: "Zapatillas",
  Boots: "Botas",
  Sandals: "Sandalias",
  Hat: "Sombrero",
  Cap: "Gorra",
  "Baseball Cap": "Gorra de béisbol",
  Gloves: "Guantes",
  Socks: "Medias",
  Scarf: "Bufanda",
  Sweater: "Suéter",
  Vest: "Chaleco",
  Suit: "Traje",
  Tie: "Corbata",
  Underwear: "Ropa interior",

  // Tecnología
  Wireless: "Inalámbrico",
  Gaming: "Gaming",
  Controller: "Control",
  Headphone: "Auricular",
  Headphones: "Auriculares",
  Earbuds: "Auriculares",
  Earbud: "Auricular",
  "Over-Ear": "Over-Ear",
  "Comfort-Fit": "Cómodo",
  Mouse: "Ratón",
  Keyboard: "Teclado",
  Monitor: "Monitor",
  Laptop: "Portátil",
  Camera: "Cámara",
  Speaker: "Altavoz",
  Charger: "Cargador",
  Cable: "Cable",
  Adapter: "Adaptador",
  Case: "Funda",
  Stand: "Soporte",
  Phone: "Teléfono",
  Tablet: "Tablet",
  Watch: "Reloj",
  Smartwatch: "Smartwatch",
  Drone: "Drone",
  Printer: "Impresora",
  Router: "Router",
  Battery: "Batería",
  Screen: "Pantalla",

  // Adjetivos/descriptivos
  Sleek: "Elegante",
  Classic: "Clásico",
  Elegant: "Elegante",
  Comfortable: "Cómodo",
  Comfortable: "Cómodo",
  Cozy: "Acogedor",
  Stylish: "Con estilo",
  Lightweight: "Liviano",
  Portable: "Portátil",
  Compact: "Compacto",
  Durable: "Resistente",
  Waterproof: "Resistente al agua",
  Smart: "Inteligente",
  Modern: "Moderno",
  Vintage: "Vintage",
  Casual: "Casual",
  Formal: "Formal",
  Sport: "Deportivo",
  Sporty: "Deportivo",
  Slim: "Delgado",
  Fitted: "Ajustado",
  Oversized: "Oversize",
  Heather: "Jaspeado",
  Solid: "Liso",
  Striped: "A rayas",
  Printed: "Estampado",
  Breathable: "Transpirable",
  Soft: "Suave",
  Warm: "Abrigado",
  Cool: "Fresco",

  // Marcadores de línea de producto
  Premium: "Premium",
  Pro: "Pro",
  Max: "Max",
  Ultra: "Ultra",
  HD: "HD",
  "4K": "4K",

  // Colores
  White: "Blanco",
  Black: "Negro",
  Blue: "Azul",
  Red: "Rojo",
  Green: "Verde",
  Silver: "Plata",
  Gold: "Oro",
  Rose: "Rosa",
  Orange: "Naranja",
  Pink: "Rosa",
  Purple: "Púrpura",
  Gray: "Gris",
  Grey: "Gris",
  Navy: "Azul marino",
  Brown: "Marrón",
  Beige: "Beige",
  Cream: "Crema",
  Teal: "Verde azulado",
  Maroon: "Bordo",
  Khaki: "Kaki",
  Olive: "Verde oliva",
  Coral: "Coral",
  Mint: "Menta",
  Lavender: "Lavanda",
  Turquoise: "Turquesa",

  // Otros
  Inked: "Con Tinta",
  Set: "Set",
  "&": "y",
  with: "con",
  and: "y",
  for: "para",
  the: "",
  in: "en",
  of: "de",
  New: "Nuevo",
  Best: "Mejor",
  Top: "Top",
  Special: "Especial",
  Limited: "Limitado",
  Edition: "Edición",
  Collection: "Colección",
  Series: "Serie",
};

export const translateProductTitle = (title) => {
  if (!title) return title;

  // primero busca frases de dos palabras antes de palabras sueltas
  let translated = title;
  const sortedKeys = Object.keys(translations).sort(
    (a, b) => b.length - a.length
  );

  sortedKeys.forEach((english) => {
    const escaped = english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`\\b${escaped}\\b`, "gi");
    translated = translated.replace(regex, translations[english]);
  });

  // limpia espacios dobles que pueden quedar al eliminar palabras como "the"
  return translated.replace(/\s+/g, " ").trim();
};
